Repository express-labs/pure-react-carousel, pull requests merged in 2023-09, with the labels that each got.

#400 Add image loading error handling capabilities to ImageWithZoom #386
  src/ImageWithZoom/ImageWithZoom.jsx
  src/ImageWithZoom/__tests__/ImageWithZoom.test.jsx
  typings/carouselElements.d.ts
Labels: work in progress

#407 Moved cancelAnimationFrame inside fakeOnDragMove
  src/Slider/Slider.jsx
Labels: under investigation, work in progress

#457 Fix bug on slider when dragging in `rtl` mode
  src/App/examples/Example14/Example14.jsx
  src/Slider/Slider.jsx
Labels: bug, work in progress
